const LazyAbout=()=>{
    return <>
    <h1>Lazy About Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis vulputate arcu, at aliquam ex. Etiam nec pharetra quam. Mauris pulvinar pretium nulla ac pellentesque. Integer non ipsum ac lacus dignissim malesuada vel ac augue. Ut justo nisi, tincidunt ac nunc et, faucibus hendrerit est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus tempus sapien vitae ligula egestas vehicula. Proin elit felis, elementum in ex eget, euismod vestibulum magna. Nullam semper purus eu pretium mollis. Praesent in blandit mauris, nec rhoncus tortor.

Cras tellus elit, dignissim porta hendrerit eu, elementum ut metus. Fusce efficitur et augue volutpat dictum. Suspendisse facilisis ut turpis eu scelerisque. Nullam sagittis tempus nisl. Aliquam tristique diam id nibh varius, tincidunt sagittis tellus auctor. Praesent euismod lacus consectetur, dapibus quam et, volutpat risus. Sed at fringilla lacus, faucibus porta sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec porttitor magna at velit euismod, et bibendum elit facilisis. Nunc euismod sed tortor a finibus. Fusce at rhoncus magna. Suspendisse maximus orci risus, in dictum leo congue quis. Donec consequat nisl eget velit pharetra condimentum. Nullam auctor hendrerit ante sed blandit. Curabitur ac massa eget lacus malesuada placerat vitae nec ex. Aenean libero tortor, egestas id leo scelerisque, rhoncus dapibus nulla.

Proin suscipit massa ligula, nec accumsan turpis volutpat non. Maecenas vel euismod felis, et pharetra quam. Mauris at porttitor quam. Suspendisse fermentum lacus velit. Mauris sapien libero, vestibulum et consectetur vitae, euismod a nulla. Donec pretium velit quis tellus convallis pulvinar. Cras ullamcorper mollis turpis tristique tempus. Ut eros lacus, sollicitudin luctus lorem ut, tincidunt tristique magna. Donec justo metus, tempus in faucibus ultrices, sollicitudin sit amet mauris.

Cras ac est in erat vestibulum auctor. Sed in feugiat ligula, quis venenatis orci. Vestibulum ultrices egestas pretium. Nulla bibendum nisl eros, in ornare lacus consequat at. Morbi sed posuere lacus, sit amet vulputate arcu. Suspendisse ligula nisl, facilisis vel justo quis, gravida condimentum magna. Etiam pretium augue sed sapien rutrum, nec vestibulum lacus auctor. Sed hendrerit dui at lectus vestibulum varius.

Donec et nunc feugiat, dictum nisl in, porttitor tellus. Morbi tempor dolor at ante imperdiet, nec luctus tellus pharetra. Nullam ut arcu ac lectus posuere posuere quis vel lacus. Donec sit amet mollis nisi. Fusce mauris risus, placerat id pulvinar id, faucibus nec metus. Curabitur non nulla semper, elementum dui sit amet, dictum quam. Nam blandit lacinia nulla, vitae sollicitudin ipsum. Integer faucibus non leo sit amet vestibulum. Nam iaculis metus lacus, at volutpat est convallis dictum. Cras congue turpis quis erat dictum, sit amet dignissim ex commodo. Praesent vestibulum libero lectus, et finibus mi aliquet at. In accumsan viverra elit, quis venenatis ipsum pulvinar a.

Pellentesque porta ipsum leo, ut ultricies neque ultrices vel. Phasellus eget ipsum non ipsum gravida placerat. Mauris dolor nisi, venenatis ac nulla nec, ullamcorper varius nisi. Ut quis sem eu metus porttitor convallis. Fusce bibendum nibh interdum, porttitor nibh ut, porttitor arcu. Aenean pellentesque mauris leo, in bibendum dui maximus et. Curabitur mi augue, commodo in erat quis, faucibus ultricies nulla. Morbi lacinia neque molestie, volutpat risus nec, accumsan eros.

Vestibulum eu elit sit amet nisi ornare ultrices. Duis rhoncus purus velit, sed tristique nulla tincidunt sed. Nullam tincidunt elit eu enim aliquam, in placerat purus lacinia. Nam semper dignissim velit. Etiam pulvinar varius pharetra. Ut vitae metus hendrerit, ullamcorper arcu vel, faucibus dolor. Nulla id porta felis. Aliquam facilisis venenatis massa. Quisque vel nisl magna. Mauris pulvinar tellus vitae purus ultricies dapibus. Vestibulum eget luctus tortor. Praesent hendrerit ullamcorper varius. In facilisis erat id hendrerit interdum. Phasellus volutpat mauris leo, nec placerat ipsum elementum nec. Duis eu imperdiet ex, at suscipit erat.

Morbi at lacinia nisl. Curabitur ornare pulvinar metus et euismod. Sed et rutrum eros. Sed vel mi ut orci imperdiet cursus. Suspendisse id nisi ut lacus iaculis porttitor vel eget odio. Nulla facilisis massa et ipsum gravida, ut eleifend velit porttitor. Curabitur a vulputate lectus. Suspendisse at tincidunt velit. Proin a purus ac augue volutpat rhoncus. Sed a semper tellus, ac accumsan elit. Donec interdum dapibus dictum. Quisque faucibus, mi vitae blandit pellentesque, eros elit mattis risus, vitae tincidunt orci lorem id enim. In hac habitasse platea dictumst. Nulla facilisi.

Nunc dignissim, elit sed sollicitudin porttitor, massa ex lacinia libero, eu consectetur velit lacus et sapien. Proin hendrerit a quam id accumsan. Integer pretium blandit augue eget blandit. Aliquam quam arcu, hendrerit id lobortis tincidunt, fringilla sit amet augue. Maecenas nec lectus odio. Nam eu augue interdum, ultrices turpis non, efficitur libero. Etiam gravida suscipit sodales. Pellentesque viverra fermentum ipsum sit amet viverra. Fusce sit amet purus in purus egestas ultrices. Proin ac accumsan nisi, ut hendrerit purus. Nullam tortor neque, consequat eget dignissim ac, porttitor in erat. Ut hendrerit, massa eget ullamcorper lacinia, purus tortor fermentum neque, a aliquet neque mauris a libero. Sed dapibus ultrices nisi, id auctor magna dictum sit amet. Praesent sed elit sem.

Aenean dapibus eros quam, ac consectetur nulla molestie quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In porta enim arcu, non feugiat magna porttitor vitae. Ut eu dignissim leo, sit amet sollicitudin ipsum. Praesent vitae nisi non neque volutpat viverra vel a dui. Suspendisse a turpis augue. Nam augue turpis, dignissim vel tempus ac, maximus et tellus. Mauris id leo accumsan, pretium lacus a, porttitor quam. Suspendisse potenti. Cras hendrerit ornare lorem, a lobortis justo placerat vitae. Vestibulum ultrices consequat ligula nec dictum. Praesent sit amet aliquet mi, in lacinia nibh. Nulla feugiat accumsan risus tempor tempor.

Donec dapibus odio ipsum, ut interdum massa commodo pulvinar. Proin vitae odio placerat, efficitur magna eu, faucibus quam. Quisque justo sapien, facilisis eget purus vel, dapibus vulputate mi. Praesent blandit ornare odio, ac feugiat libero condimentum sed. Etiam hendrerit auctor velit convallis sagittis. Vivamus et varius ante. Donec risus sem, volutpat id porttitor in, pulvinar ut mi. Mauris sollicitudin risus at lacus consequat, eu scelerisque nunc iaculis. Suspendisse imperdiet metus vel viverra sagittis. Sed elementum nunc magna, a pellentesque enim sagittis in. Nullam sed aliquet lacus, non accumsan neque. Nullam at volutpat leo. Praesent quis pulvinar mi. Quisque dapibus erat id libero tempor, eu aliquet mi tempus. Proin sit amet feugiat justo.

Maecenas risus ipsum, facilisis quis quam eget, tincidunt rhoncus augue. Quisque dapibus nisi eget lacus efficitur, et interdum tellus eleifend. Nunc accumsan nibh quis mauris laoreet suscipit id id justo. Maecenas malesuada, ipsum a tincidunt feugiat, mauris enim convallis ipsum, eget feugiat erat neque quis nisi. Phasellus massa elit, porttitor vel nisl at, ultrices auctor ligula. Fusce placerat, justo in sodales pharetra, ipsum ex rhoncus elit, eu molestie nunc erat quis purus. Sed sit amet porta nisl, non ornare lorem. Mauris fermentum augue a commodo rhoncus. Sed erat nulla, auctor ac libero non, mattis porta massa. Aliquam quis dolor orci. Aliquam sodales ultricies mauris vel viverra. Mauris mi elit, scelerisque ac risus ut, cursus tempus dui. Nullam vehicula vitae ante sed volutpat. Pellentesque sed varius orci. Vestibulum sed commodo ex. Mauris malesuada cursus diam, et vehicula ipsum placerat sit amet.

Nullam lacinia nunc at ex auctor, a varius libero condimentum. Aliquam vehicula quam est, et dapibus mauris tristique a. Duis placerat elit quis mi sagittis, pulvinar euismod mi accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse placerat maximus egestas. Aliquam pellentesque neque vel sapien tristique, nec fringilla ex suscipit. Etiam non mollis augue. Morbi lacinia cursus sem, sed pharetra libero venenatis ut. Cras augue tortor, porttitor sed vestibulum ac, porta et neque. Etiam pharetra, lacus ac convallis auctor, neque odio condimentum augue, dapibus lobortis nibh ipsum ut turpis. Curabitur neque sapien, aliquam id ex a, viverra tincidunt orci.

Suspendisse nec sagittis arcu. Sed ultricies elit at lacus vulputate, vitae semper neque commodo. Mauris arcu velit, malesuada laoreet est sed, commodo tristique risus. Sed nec diam rhoncus, molestie enim eu, feugiat augue. Ut tempor leo velit, eget mollis velit euismod vel. Mauris ut posuere ante, at dignissim erat. Proin pulvinar lacus vel urna pellentesque elementum ut quis nisi. Nunc in ornare metus. Mauris eget est in massa aliquam sodales. Nunc bibendum dapibus ornare. Sed mollis rutrum dolor, ac mollis libero. Aliquam maximus arcu non nisl fringilla cursus. In mollis eleifend aliquet. Quisque ut lacinia ante.

Duis et molestie ante. Vivamus mauris ante, dapibus sit amet interdum eget, rutrum nec turpis. Quisque et ex a augue rutrum lacinia eu sed libero. Suspendisse a augue eget nibh tempus blandit. Nullam aliquet felis nec urna rhoncus hendrerit. Cras semper augue nunc, eget sagittis dolor vehicula quis. Sed in ullamcorper ante. Nunc volutpat, eros id finibus dignissim, erat erat aliquet quam, quis pharetra lorem dui vitae ante. Nam pellentesque convallis malesuada. Fusce varius urna vitae lobortis fermentum. Praesent justo est, accumsan in est ut, mollis sollicitudin erat. Maecenas dolor nisi, viverra nec urna at, tincidunt efficitur quam. Quisque a accumsan lectus. In eu est eu ex tristique cursus ut vitae elit. Phasellus dictum efficitur tortor, a venenatis risus tempor vel. Integer est risus, lobortis sit amet leo non, volutpat gravida nunc.

Donec mattis ornare neque. Ut vitae libero consectetur, faucibus erat at, finibus lacus. In venenatis, nisl ac consequat imperdiet, arcu tortor scelerisque nibh, pharetra condimentum magna dolor non metus. Proin sit amet elit sit amet felis tempor dapibus. Integer molestie nibh sed consequat pellentesque. Ut non erat erat. Integer finibus enim ut massa lacinia interdum. Cras tincidunt orci pretium ipsum consectetur varius. Quisque vulputate pretium lorem. Nullam commodo, urna efficitur sollicitudin iaculis, diam augue venenatis risus, sed pulvinar massa sem ut ante.

Mauris eget urna nisl. Ut auctor metus id sapien aliquet, sit amet pulvinar odio egestas. Ut ex diam, imperdiet sit amet enim id, euismod iaculis arcu. Nam a massa eu est viverra semper nec et erat. Aliquam turpis arcu, volutpat id viverra quis, ornare ut leo. Pellentesque erat velit, tincidunt ac egestas quis, accumsan posuere risus. Nullam laoreet nisl ligula, at euismod erat efficitur quis. Maecenas semper eget tellus ac condimentum. Suspendisse potenti.

Proin lobortis mi ut neque laoreet blandit. Cras dapibus dictum ligula, id scelerisque libero tincidunt in. Donec interdum nec dolor ac vehicula. Quisque vitae nibh felis. Aliquam non maximus turpis. Nullam consequat ligula a justo convallis fermentum. Maecenas tincidunt ligula quis ex sagittis hendrerit a quis nisi. Aliquam molestie neque eget orci facilisis vestibulum. Quisque non commodo ex, nec viverra est. Maecenas sed suscipit dolor. Etiam massa neque, pretium quis est in, sodales maximus sapien. Quisque placerat gravida nibh at lobortis. Duis porta vehicula pulvinar.

Phasellus eget lorem a nisl ultrices ullamcorper. Aliquam quis purus in orci euismod pharetra. Donec ut nibh sem. Fusce id condimentum lorem, at rhoncus velit. Pellentesque iaculis sapien ac felis pharetra, quis sollicitudin ipsum hendrerit. Praesent convallis, nisi sit amet posuere dictum, sem eros tristique magna, fringilla vehicula enim dolor ut lacus. Aliquam laoreet feugiat orci, quis sollicitudin dolor tincidunt nec. Sed erat augue, rutrum eget auctor ac, elementum sed nisl. Nullam tortor nisi, viverra et tortor vitae, luctus egestas neque. Sed quis feugiat dui, non malesuada magna. Sed auctor, urna a lacinia porta, nulla leo aliquam metus, et posuere justo magna at justo. Aenean sed imperdiet nisi, in vestibulum orci. Pellentesque sed ex a tortor feugiat imperdiet at ut lectus. Nullam sollicitudin, velit in condimentum sollicitudin, metus ligula accumsan dolor, et iaculis nulla erat in elit. Nulla facilisi. Aenean gravida nibh tincidunt sapien blandit hendrerit.

Donec tincidunt hendrerit purus sed varius. Maecenas porttitor cursus enim, dignissim placerat arcu hendrerit nec. Nam feugiat, est sed sodales convallis, arcu turpis aliquet dolor, id congue risus orci id nibh. Etiam tellus neque, elementum sed risus eget, scelerisque sagittis nibh. Etiam massa nisl, luctus nec vestibulum eget, varius sit amet sapien. Pellentesque elit ipsum, mattis eu vehicula vel, vehicula nec diam. Vivamus sit amet sagittis velit. Suspendisse id lobortis nulla. Duis non nunc ut tortor rhoncus ultricies sed non nulla.

Generated 20 paragraphs, 1972 words, 13246 bytes of Lorem Ipsum
</p>
    </>
}

export default LazyAbout;